import type { ActivePlan, Store } from './storage'
import type { Workout } from './data'

const easternDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const shiftDate=(date:string,days:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}

export type ReviewNotes={goals:string;recovery:string;equipment:string;constraints:string;pain:string}
export function downloadText(name:string,text:string,type:string){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
const mean=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null
export function makeCoachReview(store:Store,activeWorkouts:Workout[],weeks:2|4,notes:ReviewNotes){
  const to=easternDate(),from=shiftDate(to,-(weeks*7-1))
  const sessions=store.workouts.filter(w=>w.date>=from&&w.date<=to),completed=sessions.filter(w=>w.completed)
  const exerciseMap=new Map(activeWorkouts.flatMap(w=>w.exercises).map(e=>[e.id,e.name]))
  const exerciseResults=[...new Set(sessions.flatMap(s=>s.exercises.map(e=>e.exerciseId)))].map(id=>{const logs=sessions.flatMap(s=>s.exercises.filter(e=>e.exerciseId===id).map(e=>({date:s.date,...e}))).sort((a,b)=>a.date.localeCompare(b.date));const done=logs.flatMap(l=>l.sets.filter(s=>s.done));const latest=logs.at(-1)?.sets.filter(s=>s.done)||[];return {exercise:exerciseMap.get(id)||id,sessions:logs.length,recentWorkingLoad:latest[0]?.weight??null,recentReps:latest.map(s=>s.reps),averageRir:mean(done.map(s=>s.rir)),completedSets:done.length}})
  const nutrition=store.nutrition.filter(n=>n.date>=from&&n.date<=to),measurements=store.measurements.filter(m=>m.date>=from&&m.date<=to).sort((a,b)=>a.date.localeCompare(b.date));const weights=measurements.map(m=>m.weight),waists=measurements.flatMap(m=>m.waist==null?[]:[m.waist])
  return {schemaVersion:'fittrack-coach-review-v1',generatedAt:new Date().toISOString(),period:{weeks,from,to},profile:{dietaryConstraints:['Indian diet','chicken only for meat','eggs allowed','no pork','no beef','no fish','no soy'],gymSchedule:'Monday, Tuesday, Thursday, Friday at 7:00 PM Eastern'},adherence:{workoutsCompleted:completed.length,workoutsLogged:sessions.length,plannedWorkouts:weeks*4,workoutCompletionRate:completed.length/(weeks*4),nutritionDaysLogged:nutrition.length,daysAtOrAbove140gProtein:nutrition.filter(n=>n.protein>=140).length,averageLoggedProtein:mean(nutrition.map(n=>n.protein)),averageLoggedCalories:mean(nutrition.map(n=>n.calories))},exerciseResults,bodyTrends:{weightReadings:weights.length,firstWeight:weights[0]??null,latestWeight:weights.at(-1)??null,weightChange:weights.length>1?weights.at(-1)!-weights[0]:null,waistReadings:waists.length,firstWaist:waists[0]??null,latestWaist:waists.at(-1)??null,waistChange:waists.length>1?waists.at(-1)!-waists[0]:null},notes,privacy:{photosIncluded:false,rawWorkoutRowsIncluded:false,rawMealRowsIncluded:false}}
}
export function reviewPrompt(){return `You are reviewing a FitTrack training block. Use only the attached aggregate coach-review data. Create a safe, conservative 2-4 week plan for hypertrophy and body recomposition. Preserve these constraints: Indian diet; chicken is the only meat; eggs and dairy are allowed; no pork, beef, fish, or soy. Use the fittrack-plan-v1 JSON schema shown below. Do not include prose outside the JSON. Keep weight increases conservative and explain exercise cues in plain language.\n\nRequired top-level fields: schemaVersion, planId, name, startDate, endDate, dietaryConstraints, workouts, mealsByDay. Each workout requires id, day (0-6), title, focus, tone (green or blue), and exercises. Each exercise requires id, name, sets, minReps, maxReps, rest, cue, increment, and optional startingWeight. mealsByDay keys are 0-6 and each meal requires id, time, name, detail, calories, and protein.`}
export function reviewMarkdown(review:ReturnType<typeof makeCoachReview>){return `# FitTrack Coach Review\n\nGenerated: ${review.generatedAt}\nPeriod: ${review.period.from} to ${review.period.to} (${review.period.weeks} weeks)\n\n## Planning prompt\n\n${reviewPrompt()}\n\n## Aggregate review data\n\n\`\`\`json\n${JSON.stringify(review,null,2)}\n\`\`\`\n`}
export function validatePlan(value:unknown):{plan?:ActivePlan;errors:string[]}{const errors:string[]=[];if(!value||typeof value!=='object')return{errors:['File must contain a JSON object.']};const p=value as Partial<ActivePlan>;if(p.schemaVersion!=='fittrack-plan-v1')errors.push('schemaVersion must be fittrack-plan-v1.');if(!p.planId||!p.name)errors.push('planId and name are required.');if(!p.startDate||!p.endDate||p.startDate>p.endDate)errors.push('Valid startDate and endDate are required.');if(!Array.isArray(p.workouts)||!p.workouts.length)errors.push('At least one workout is required.');else for(const [wi,w] of p.workouts.entries()){if(!Number.isInteger(w.day)||w.day<0||w.day>6)errors.push(`Workout ${wi+1}: day must be 0-6.`);if(!Array.isArray(w.exercises)||!w.exercises.length)errors.push(`Workout ${wi+1}: exercises are required.`);else for(const [ei,e] of w.exercises.entries()){if(!e.id||!e.name)errors.push(`Workout ${wi+1}, exercise ${ei+1}: id and name required.`);if(!(e.sets>=1&&e.sets<=8))errors.push(`${e.name||'Exercise'}: sets must be 1-8.`);if(!(e.minReps>=1&&e.maxReps>=e.minReps&&e.maxReps<=30))errors.push(`${e.name||'Exercise'}: invalid rep range.`);if(!(e.increment>0&&e.increment<=20))errors.push(`${e.name||'Exercise'}: increment must be >0 and <=20.`)}}if(!p.mealsByDay||typeof p.mealsByDay!=='object')errors.push('mealsByDay is required.');else for(let d=0;d<7;d++){const meals=p.mealsByDay[String(d)];if(!Array.isArray(meals)||!meals.length)errors.push(`mealsByDay.${d} requires at least one meal.`);else for(const m of meals){const soy=`${m.name} ${m.detail}`.toLowerCase();if(/\b(soy|tofu|tempeh|edamame)\b/.test(soy))errors.push(`${m.name}: soy foods are not allowed.`);if(m.calories<0||m.protein<0)errors.push(`${m.name}: calories and protein cannot be negative.`)}}return errors.length?{errors}:{plan:p as ActivePlan,errors}}
