import { useMemo, useState } from 'react'
import type { Store } from './storage'
import type { Workout } from './data'
import { downloadText, makeCoachReview, reviewMarkdown, reviewPrompt, type ReviewNotes } from './coach'

export default function CoachReview({store,activeWorkouts}:{store:Store;activeWorkouts:Workout[]}){
  const [weeks,setWeeks]=useState<2|4>(4),[notes,setNotes]=useState<ReviewNotes>({goals:'Build muscle while keeping waist gain controlled.',recovery:'',equipment:'',constraints:'Chicken only for meat; eggs and dairy allowed; no soy.',pain:''})
  const review=useMemo(()=>makeCoachReview(store,activeWorkouts,weeks,notes),[store,activeWorkouts,weeks,notes])
  const field=(key:keyof ReviewNotes,label:string,placeholder:string)=><label><span>{label}</span><textarea value={notes[key]} onChange={e=>setNotes({...notes,[key]:e.target.value})} placeholder={placeholder}/></label>
  return <section className="coach-review panel"><div className="panel-head"><div><span className="eyebrow">COACH REVIEW</span><h3>Prepare the next training block</h3></div><div className="period-toggle"><button className={weeks===2?'active':''} onClick={()=>setWeeks(2)}>2 weeks</button><button className={weeks===4?'active':''} onClick={()=>setWeeks(4)}>4 weeks</button></div></div><p className="muted">This export contains aggregate trends and recent working loads. It excludes photographs and raw workout or meal rows.</p><div className="review-preview"><div><small>Workout adherence</small><b>{Math.round(review.adherence.workoutCompletionRate*100)}%</b><span>{review.adherence.workoutsCompleted}/{review.adherence.plannedWorkouts} planned</span></div><div><small>Exercises tracked</small><b>{review.exerciseResults.length}</b><span>aggregate results</span></div><div><small>Protein adherence</small><b>{review.adherence.daysAtOrAbove140gProtein}</b><span>days at 140g+</span></div><div><small>Weight trend</small><b>{review.bodyTrends.weightChange==null?'—':`${review.bodyTrends.weightChange>=0?'+':''}${review.bodyTrends.weightChange.toFixed(1)} lb`}</b><span>{review.bodyTrends.weightReadings} readings</span></div></div><details><summary>Exercise aggregate preview</summary><div className="aggregate-table">{review.exerciseResults.length?review.exerciseResults.map(e=><div key={e.exercise}><b>{e.exercise}</b><span>{e.sessions} sessions</span><span>{e.recentWorkingLoad??'—'} kg recent</span><span>{e.completedSets} sets</span></div>):<p className="muted">No completed exercise data exists in this period yet.</p>}</div></details><div className="review-notes">{field('goals','Current goals','What should the next block prioritize?')}{field('recovery','Recovery notes','Sleep, soreness, fatigue, schedule...')}{field('equipment','Equipment changes','New or unavailable machines...')}{field('constraints','Constraints','Diet, time, movement preferences...')}{field('pain','Pain or movement flags','Record pain location and movements affected. Do not diagnose.')}</div><details><summary>Reusable ChatGPT planning prompt</summary><pre className="prompt-preview">{reviewPrompt()}</pre></details><div className="button-row"><button className="primary" onClick={()=>downloadText('coach-review.md',reviewMarkdown(review),'text/markdown')}>Export coach-review.md</button><button className="secondary" onClick={()=>downloadText('coach-review.json',JSON.stringify(review,null,2),'application/json')}>Export coach-review.json</button></div></section>
}
