import { useMemo, useState } from 'react'
import type { Store } from './storage'
import type { Workout } from './data'
import { downloadText, makeCoachReview, validatePlan } from './coach'

export default function GeminiCoach({store,activeWorkouts}:{store:Store;activeWorkouts:Workout[]}){
  const [question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState<'ask'|'generate-plan'|'plan'|''>('')
  const review=useMemo(()=>makeCoachReview(store,activeWorkouts,4,{goals:'Build muscle while keeping waist gain controlled.',recovery:'',equipment:'',constraints:'Chicken only for meat; eggs and dairy allowed; no soy.',pain:''}),[store,activeWorkouts])
  const call=async(action:'ask'|'generate-plan')=>{setBusy(action);setError('');if(action==='ask')setAnswer('');try{const response=await fetch('/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,question,review})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');if(action==='ask')setAnswer(data.text);else{let parsed;try{parsed=JSON.parse(data.text)}catch{throw new Error('Gemini returned plan text that was not valid JSON.')}const validation=validatePlan(parsed);if(validation.errors.length)throw new Error(`Generated plan did not pass validation: ${validation.errors.slice(0,3).join(' ')}`);downloadText('fittrack-gemini-plan.json',JSON.stringify(validation.plan,null,2),'application/json')}}catch(e){setError(e instanceof Error?e.message:'The request failed.')}finally{setBusy('')}}
  return <section className="panel gemini-coach"><div className="panel-head"><div><span className="eyebrow">GEMINI · AGGREGATE CONTEXT ONLY</span><h3>AI Coach</h3></div><span className="mini-status">Optional</span></div><p className="muted">Questions send your privacy-minimized four-week Coach Review to Gemini. Photos and raw workout or meal rows are not included.</p><label className="coach-question"><span>Ask about your training, nutrition, or trends</span><textarea maxLength={1200} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Example: Why has my chest press stalled, and what should I change next week?"/></label><div className="button-row"><button className="primary" disabled={!question.trim()||!!busy} onClick={()=>call('ask')}>{busy==='ask'?'Asking Gemini…':'Ask Coach'}</button><button className="secondary" disabled={!!busy} onClick={()=>call('generate-plan')}>{busy==='plan'?'Generating…':'Generate next plan JSON'}</button></div>{error&&<div className="ai-error">{error}</div>}{answer&&<div className="ai-answer"><b>Coach response</b><p>{answer}</p></div>}<p className="ai-caveat">AI suggestions are reviewed by you. Generated plans are downloaded and must still pass FitTrack’s import comparison before activation.</p></section>
}
