import { useRef, useState } from 'react'
import type { ActivePlan, Store } from './storage'
import type { Workout } from './data'
import { validatePlan } from './coach'

export default function PlanImporter({store,setStore,currentWorkouts,toast}:{store:Store;setStore:(s:Store)=>void;currentWorkouts:Workout[];toast:(s:string)=>void}){
  const input=useRef<HTMLInputElement>(null),[candidate,setCandidate]=useState<ActivePlan|null>(null),[errors,setErrors]=useState<string[]>([])
  const read=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const result=validatePlan(JSON.parse(String(reader.result)));setErrors(result.errors);setCandidate(result.plan||null)}catch{setErrors(['The selected file is not valid JSON.']);setCandidate(null)}};reader.readAsText(file)}
  const currentExercises=currentWorkouts.reduce((a,w)=>a+w.exercises.length,0),nextExercises=candidate?.workouts.reduce((a,w)=>a+w.exercises.length,0)||0
  const activate=()=>{if(!candidate)return;if(!confirm(`Activate “${candidate.name}”? Your existing history will be preserved.`))return;setStore({...store,activePlan:{...candidate,activatedAt:new Date().toISOString()}});setCandidate(null);toast('New plan activated')}
  return <section className="panel plan-importer"><div className="panel-head"><div><span className="eyebrow">IMPORT NEXT PLAN</span><h3>Validate, compare, then activate</h3></div><span className="mini-status">fittrack-plan-v1</span></div><p className="muted">Import the JSON returned by ChatGPT. FitTrack checks dates, workout structure, rep and set limits, increments, daily meals, and your no-soy rule. Nothing activates automatically.</p><button className="secondary" onClick={()=>input.current?.click()}>Choose plan JSON</button><input ref={input} hidden type="file" accept="application/json,.json" onChange={e=>read(e.target.files?.[0])}/>{errors.length>0&&<div className="validation-errors"><b>Plan cannot be activated</b><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}{candidate&&<div className="plan-comparison"><div><small>Current plan</small><b>{store.activePlan?.name||'4-Week Build'}</b><span>{currentWorkouts.length} days · {currentExercises} exercises</span></div><div className="compare-arrow">→</div><div><small>Imported plan</small><b>{candidate.name}</b><span>{candidate.workouts.length} days · {nextExercises} exercises</span></div><div className="comparison-details"><span>{candidate.startDate} to {candidate.endDate}</span><span>{Object.values(candidate.mealsByDay).flat().length} planned meal slots</span><span>{candidate.dietaryConstraints.join(' · ')}</span></div><button className="primary" onClick={activate}>Activate imported plan</button></div>}</section>
}
